# Generated by Django 4.0.6 on 2022-08-23 02:45

from django.db import migrations, models
import django.db.models.functions.datetime
import ecommerce.behaviours
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='catergory',
            name='created',
            field=ecommerce.behaviours.AutoCreatedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='catergory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='catergory',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='catergory',
            name='modified',
            field=ecommerce.behaviours.AutoLastModifiedField(default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='catergory',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='productincart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='productincart',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='deleted'),
        ),
    ]
